#ifndef __OPCODES_H
#define __OPCODES_H

enum opcodes {
	nop = 0,
	add = 1,
	add_with_carry = 2,
	add_big_literal = 3,
	add_big_literal_with_carry = 4,
	sub = 5,
	sub_with_carry = 6,
	sub_big_literal = 7,
	sub_big_literal_with_carry = 8,
	sub_big_literal_reverse = 9,
	sub_big_literal_with_carry_reverse = 10,
	or = 11,
	or_big_literal = 12,
	xor = 13,
	xor_big_literal = 14,
	and = 15,
	and_big_literal = 16,
	shift_left = 17,
	shift_right = 18,
	mov = 19,
	mov_on_equal = 20,
	mov_on_not_equal = 21,
	mov_on_less_then = 22,
	mov_on_less_then_or_equal = 23,
	mov_big_literal = 24,
	mov_big_literal_on_equal = 25,
	mov_big_literal_on_not_equal = 26,
	mov_big_literal_on_less_then = 27,
	mov_big_literal_on_less_then_or_equal = 28,
	cmp = 29,
	cmp_big_literal = 30,
	cmp_big_literal_reverse = 31,
	load = 32,
	load_big_literal = 33,
	load_with_offset = 34,
	store = 36,
	store_big_literal = 37,
	store_with_offset = 38,
	call = 40,
	call_big_literal = 41,
	retfie = 42,
	intenable = 43,
	intdisable = 44
};

#endif
