
// This file has been generated by the GUI designer. Do not modify.
namespace ESC64VM
{
	public partial class ESCWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action OpenAction;
		private global::Gtk.Action jumpToAction;
		private global::Gtk.VBox rootVBox;
		private global::Gtk.MenuBar menuBar;
		private global::Gtk.Toolbar toolBar;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView registerTable;
		private global::Gtk.HPaned hpaned2;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry programTableFrom;
		private global::Gtk.Entry programTableTo;
		private global::Gtk.Button programTableUpdateButton;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.NodeView programTable;
		private global::Gtk.HPaned hpaned3;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Entry memoryTableFrom;
		private global::Gtk.Entry memoryTableTo;
		private global::Gtk.Button memoryTableUpdateButton;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.NodeView memoryTable;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.NodeView breakPointTable;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ESC64VM.ESCWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
			this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
			w1.Add (this.OpenAction, null);
			this.jumpToAction = new global::Gtk.Action ("jumpToAction", global::Mono.Unix.Catalog.GetString ("Step"), null, "gtk-jump-to");
			this.jumpToAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Step");
			w1.Add (this.jumpToAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "ESC64VM.ESCWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ESCWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ESC64VM.ESCWindow.Gtk.Container+ContainerChild
			this.rootVBox = new global::Gtk.VBox ();
			this.rootVBox.Name = "rootVBox";
			this.rootVBox.Spacing = 6;
			// Container child rootVBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menuBar'><menu name='FileAction' action='FileAction'><menuitem name='OpenAction' action='OpenAction'/></menu></menubar></ui>");
			this.menuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menuBar")));
			this.menuBar.Name = "menuBar";
			this.rootVBox.Add (this.menuBar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.rootVBox [this.menuBar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child rootVBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolBar'><toolitem name='jumpToAction' action='jumpToAction'/></toolbar></ui>");
			this.toolBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolBar")));
			this.toolBar.Name = "toolBar";
			this.toolBar.ShowArrow = false;
			this.rootVBox.Add (this.toolBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.rootVBox [this.toolBar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child rootVBox.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 134;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.registerTable = new global::Gtk.NodeView ();
			this.registerTable.CanFocus = true;
			this.registerTable.Name = "registerTable";
			this.GtkScrolledWindow.Add (this.registerTable);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
			w5.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 276;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.programTableFrom = new global::Gtk.Entry ();
			this.programTableFrom.CanFocus = true;
			this.programTableFrom.Name = "programTableFrom";
			this.programTableFrom.Text = global::Mono.Unix.Catalog.GetString ("0");
			this.programTableFrom.IsEditable = true;
			this.programTableFrom.InvisibleChar = '•';
			this.hbox1.Add (this.programTableFrom);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.programTableFrom]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.programTableTo = new global::Gtk.Entry ();
			this.programTableTo.CanFocus = true;
			this.programTableTo.Name = "programTableTo";
			this.programTableTo.Text = global::Mono.Unix.Catalog.GetString ("10");
			this.programTableTo.IsEditable = true;
			this.programTableTo.InvisibleChar = '•';
			this.hbox1.Add (this.programTableTo);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.programTableTo]));
			w7.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.programTableUpdateButton = new global::Gtk.Button ();
			this.programTableUpdateButton.CanFocus = true;
			this.programTableUpdateButton.Name = "programTableUpdateButton";
			this.programTableUpdateButton.UseUnderline = true;
			this.programTableUpdateButton.Label = global::Mono.Unix.Catalog.GetString ("Update");
			this.hbox1.Add (this.programTableUpdateButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.programTableUpdateButton]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.programTable = new global::Gtk.NodeView ();
			this.programTable.CanFocus = true;
			this.programTable.Name = "programTable";
			this.GtkScrolledWindow1.Add (this.programTable);
			this.vbox1.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow1]));
			w11.Position = 1;
			this.hpaned2.Add (this.vbox1);
			global::Gtk.Paned.PanedChild w12 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.vbox1]));
			w12.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.hpaned3 = new global::Gtk.HPaned ();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 322;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.memoryTableFrom = new global::Gtk.Entry ();
			this.memoryTableFrom.CanFocus = true;
			this.memoryTableFrom.Name = "memoryTableFrom";
			this.memoryTableFrom.Text = global::Mono.Unix.Catalog.GetString ("0");
			this.memoryTableFrom.IsEditable = true;
			this.memoryTableFrom.InvisibleChar = '•';
			this.hbox2.Add (this.memoryTableFrom);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.memoryTableFrom]));
			w13.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.memoryTableTo = new global::Gtk.Entry ();
			this.memoryTableTo.CanFocus = true;
			this.memoryTableTo.Name = "memoryTableTo";
			this.memoryTableTo.Text = global::Mono.Unix.Catalog.GetString ("10");
			this.memoryTableTo.IsEditable = true;
			this.memoryTableTo.InvisibleChar = '•';
			this.hbox2.Add (this.memoryTableTo);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.memoryTableTo]));
			w14.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.memoryTableUpdateButton = new global::Gtk.Button ();
			this.memoryTableUpdateButton.CanFocus = true;
			this.memoryTableUpdateButton.Name = "memoryTableUpdateButton";
			this.memoryTableUpdateButton.UseUnderline = true;
			this.memoryTableUpdateButton.Label = global::Mono.Unix.Catalog.GetString ("Update");
			this.hbox2.Add (this.memoryTableUpdateButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.memoryTableUpdateButton]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.memoryTable = new global::Gtk.NodeView ();
			this.memoryTable.CanFocus = true;
			this.memoryTable.Name = "memoryTable";
			this.GtkScrolledWindow2.Add (this.memoryTable);
			this.vbox2.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow2]));
			w18.Position = 1;
			this.hpaned3.Add (this.vbox2);
			global::Gtk.Paned.PanedChild w19 = ((global::Gtk.Paned.PanedChild)(this.hpaned3 [this.vbox2]));
			w19.Resize = false;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.breakPointTable = new global::Gtk.NodeView ();
			this.breakPointTable.CanFocus = true;
			this.breakPointTable.Name = "breakPointTable";
			this.GtkScrolledWindow3.Add (this.breakPointTable);
			this.hpaned3.Add (this.GtkScrolledWindow3);
			this.hpaned2.Add (this.hpaned3);
			this.hpaned1.Add (this.hpaned2);
			this.rootVBox.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.rootVBox [this.hpaned1]));
			w24.Position = 2;
			this.Add (this.rootVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 965;
			this.DefaultHeight = 496;
			this.Show ();
			this.OpenAction.Activated += new global::System.EventHandler (this.OpenActivated);
			this.jumpToAction.Activated += new global::System.EventHandler (this.OnStep);
			this.programTableUpdateButton.Clicked += new global::System.EventHandler (this.programTableUpdateClick);
			this.memoryTableUpdateButton.Clicked += new global::System.EventHandler (this.MemoryTableUpdateButtonPressed);
		}
	}
}
