vm.exe:	*.cs
	mono-csc	-out:vm.exe\
				-main:ESC64VM.Program\
				*.cs\
				/r:/usr/lib/cli/gtk-sharp-2.0/gtk-sharp.dll\
				/r:/usr/lib/cli/glib-sharp-2.0/glib-sharp.dll\
				/r:/usr/lib/cli/gdk-sharp-2.0/gdk-sharp.dll\
				/r:/usr/lib/mono/4.0/Mono.Posix.dll\
				/r:/usr/lib/mono/4.0/System.Core.dll

