.SUFFIXES:
.SECONDARY:

#comment PROGRAM to just create object files
PROGRAM			:= testprgm
OBJECTS			:= test.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= 
STDESC			:= ../stdesc
STDESC_OBJS		:= generic-printf.o sprintf.o itoa.o puts.o varargs.o printf.o putchar.o
ESCIO			:= ../escio
LINK			:= 

include ../esc64-build.mk
