.SUFFIXES:
.SECONDARY:

PROGRAM			:= echo
OBJECTS			:= echo.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= 
STDESC			:= ../stdesc
STDESC_OBJS		:= puts.o getchar.o itoa.o memset.o
ESCIO			:= ../escio
LINK			:= 

.PHONY: all
all: esc64_lst

.PHONY: clean
clean: esc64_clean

include ../esc64-build-v2.mk

