#include <mini_assembler.h>
#include <cpu.h>

/*
 * R_LAST_KNOWN_PRIME: last known prime number
 * R_CURRENT_CHECKING: current checking against trial division
 * R_ITTERATOR: itterator for prime array
 * R_LEN_ARR:	length prime array
 * R_TMP0: tmp0
 * R_TMP1: tmp1
 * R_ARR: pointer to prime array
 */

#define R_LAST_KNOWN_PRIME GP0
#define R_CURRENT_CHECKING GP1
#define R_ITTERATOR	GP2
#define R_LEN_ARR GP3
#define R_TMP0 GP4
#define R_TMP1 GP5
#define R_ARR GP6


void asm_prgm(void)
{
	mov_literal(R_ARR, 0x0800);
	mov(R_LEN_ARR, R_ARR);
	mov_literal(R_CURRENT_CHECKING, 1);

	lbl("try_next");
	mov_literal(R_TMP0, 2);
	add(R_CURRENT_CHECKING, R_CURRENT_CHECKING, R_TMP0);
	mov(R_ITTERATOR, R_ARR);

	lbl("try_next_divisor");

	sub(R_TMP0, R_ITTERATOR, R_LEN_ARR);
	mov_literal_labeled(R_TMP0, "found_prime");
	mov_on_zero(PC, R_TMP0);

	mov(R_TMP0, R_CURRENT_CHECKING);
#define SUB_SHIFTED_DIVISOR(x) \
	load(R_TMP1, R_ITTERATOR);\
	sub(R_TMP1, R_TMP0, R_TMP1);\
	mov_literal_labeled(R_TMP1, "try_next");\
	mov_on_zero(PC, R_TMP1);\
	mov_literal_labeled(R_TMP1, "underflow"#x);\
	mov_on_not_carry(PC, R_TMP1);\
	load(R_TMP1, R_ITTERATOR);\
	sub(R_TMP0, R_TMP0, R_TMP1);\
	lbl("underflow"#x);\
	mov_literal(R_TMP1, 1);\
	add(R_ITTERATOR, R_ITTERATOR, R_TMP1)

	SUB_SHIFTED_DIVISOR(0);
	SUB_SHIFTED_DIVISOR(1);
	SUB_SHIFTED_DIVISOR(2);
	SUB_SHIFTED_DIVISOR(3);
	SUB_SHIFTED_DIVISOR(4);
	SUB_SHIFTED_DIVISOR(5);
	SUB_SHIFTED_DIVISOR(6);
	SUB_SHIFTED_DIVISOR(7);
	SUB_SHIFTED_DIVISOR(8);
	SUB_SHIFTED_DIVISOR(9);
	SUB_SHIFTED_DIVISOR(10);
	SUB_SHIFTED_DIVISOR(11);
	SUB_SHIFTED_DIVISOR(12);
	SUB_SHIFTED_DIVISOR(13);
	SUB_SHIFTED_DIVISOR(14);

	load(R_TMP1, R_ITTERATOR);
	sub(R_TMP1, R_TMP0, R_TMP1);
	mov_literal_labeled(R_TMP1, "try_next");
	mov_on_zero(PC, R_TMP1);
	mov_literal(R_TMP1, 1);
	add(R_ITTERATOR, R_ITTERATOR, R_TMP1);

	mov_literal_labeled(PC, "try_next_divisor");

	lbl("found_prime");
	mov(R_LAST_KNOWN_PRIME, R_CURRENT_CHECKING);
	mov_literal(R_TMP0, 16);
	add(R_LEN_ARR, R_LEN_ARR, R_TMP0);
	mov_literal(R_TMP0, 15);
	add(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	mov_literal(R_TMP0, 1);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//0
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//1
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//2
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//3
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//4
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//5
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//6
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//7
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//8
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//9
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//10
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//11
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//12
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//13
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//14
	shiftl(R_CURRENT_CHECKING, R_CURRENT_CHECKING);
	sub(R_ITTERATOR, R_ITTERATOR, R_TMP0);
	store(R_ITTERATOR, R_CURRENT_CHECKING);//15

	mov(R_CURRENT_CHECKING, R_LAST_KNOWN_PRIME);
	mov_literal_labeled(PC, "try_next");
	

	halt();
}
