.SUFFIXES:
.SECONDARY:

#PROGRAM			:= 
OBJECTS			:= base64_dec.o base64_enc.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= -Iinclude
STDESC			:= ../stdesc
STDESC_OBJS		:= 
ESCIO			:= ../escio
LINK			:= 

include ../esc64-build.mk

