.SUFFIXES:
.SECONDARY:

PROGRAM			:= delaytest
OBJECTS			:= main.o delay.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= 
STDESC			:= ../stdesc
STDESC_OBJS		:= printf.o putchar.o generic-printf.o varargs.o puts.o
ESCIO			:= ../escio
LINK			:=

include ../esc64-build.mk

