.SUFFIXES:
.SECONDARY:

COMMON			:= ../common

PROGRAM			:= testprgm
OBJECTS			:= test.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= -I$(COMMON)
STDESC			:= ../stdesc
STDESC_OBJS		:= 
ESCIO			:= ../escio
LINK			:= $(COMMON)/esctest.o $(COMMON)/vio.o

include ../esc64-build.mk
