.SUFFIXES:
.SECONDARY:

PROGRAM			:= prgm
OBJECTS			:= main.o copyandcount.o data.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= 
STDESC			:= ../stdesc
STDESC_OBJS		:= 
ESCIO			:= ../escio
LINK			:= 

include ../esc64-build.mk

