.SUFFIXES:
.SECONDARY:

OBJECTS			:= escio.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= 
STDESC			:= ../stdesc
STDESC_OBJS		:= atoi.o rand.o fgets.o toupper.o puts.o itoa.o isdigit.o getchar.o fputs.o putchar.o
ESCIO			:= ../escio
LINK			:= 

.PHONY: all
all: esc64_objs

.PHONY: clean
clean: esc64_clean

include ../esc64-build-v2.mk

