.SUFFIXES:
.SECONDARY:

OBJECTS			:= escio.o
CRT_PATH		:= ../../crt
GPP_FLAGS		:= 
CFLAGS			:= 
STDESC			:= ../stdesc
STDESC_OBJS		:= atoi.o rand.o fgets.o toupper.o puts.o itoa.o isdigit.o getchar.o fputs.o putchar.o
ESCIO			:= ../escio
LINK			:= 

include ../esc64-build.mk

